[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dynamic_test_linking = true

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@powers/=lib/powers/solidity/src/",
    "@powers-test/=lib/powers/solidity/test/",
    "@powers-script/=lib/powers/solidity/script/",
    "@forge-std/=lib/forge-std/src/",
    "@solady/=lib/solady/src/",
    "@solbase/=lib/solbase/src/"
]

# Compiler settings
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing configuration
gas_reports = ["*"]
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

# Fuzz testing
[fuzz]
runs = 1000
max_test_rejects = 65536

# Invariant testing
[invariant]
runs = 256
depth = 15
fail_on_revert = false
show_metrics = true

# Linting
[profile.default.lint]
exclude_lints = []

# RPC endpoints for different networks
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
mantle = "${MANTLE_RPC_URL}"
mantle_testnet = "${MANTLE_TESTNET_RPC_URL}"

# Etherscan verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
mantle = { key = "${MANTLESCAN_API_KEY}", url = "https://api.mantlescan.xyz/api" }
